# This test creates notebooks in the workspace, creates a job referencing them,
# then uses bundle generate and bind to manage the job through DABs.

RequiresUnityCatalog = true

Ignore = [
    "resources/*",
    "src/*",
]

[Env]
MSYS_NO_PATHCONV = "1"

[[Repls]]
Old = '\\'
New = '/'
