Cloud = true
Local = true
RecordRequests = false

# Use FakeWorkspace handlers for secrets which properly maintain state
EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["terraform", "direct"]

Ignore = [
    "databricks.yml",
]
