[[Server]]
Pattern = "POST /api/2.0/sql/statements"
Response.Body = '''
{
  "statement_id": "stmt-2",
  "status": {"state": "SUCCEEDED"},
  "manifest": {
    "schema": {
      "column_count": 2,
      "columns": [
        {"name": "letter"},
        {"name": "num"}
      ]
    },
    "total_row_count": 2,
    "truncated": true
  },
  "result": {
    "chunk_index": 0,
    "data_array": [
      ["a", "1"],
      ["b", "2"]
    ],
    "row_count": 2
  }
}
'''

[[Server]]
Pattern = "GET /api/2.0/sql/statements/stmt-2/result/chunks/0"
Response.Body = '''
{
  "chunk_index": 0,
  "data_array": [
    ["a", "1"],
    ["b", "2"]
  ]
}
'''
