sync: {paths: []} # dont need to copy files

resources:
  jobs:
    my_job:
      name: My Job
      tasks:
        - task_key: my_notebook
          notebook_task:
            notebook_path: my_notebook.py
