Local = true
Cloud = false

[Env]
MSYS_NO_PATHCONV = "1"

[[Server]]
Pattern = "GET /api/2.0/workspace/list"
Response.Body = '''
{
  "objects": [
    {
      "path": "/test-dir/experiment",
      "object_type": "MLFLOW_EXPERIMENT",
      "object_id": 125
    }
  ]
}
'''

[[Server]]
Pattern = "GET /api/2.0/workspace/get-status"
Response.Body = '''
{
  "path": "/test-dir",
  "object_type": "DIRECTORY",
  "object_id": 123
}
'''
