Local = true
Env.DATABRICKS_CLI_TEST_PID = "1"

[[Server]]
Pattern = "GET /api/2.0/workspace/list"
KillCaller = 9

[[Repls]]
Old = 'script: line \d+: \d+ Killed'
New = 'script: line [N]: [PID] Killed'
