bundle:
  name: wal-multi-crash-test

resources:
  jobs:
    test_job:
      name: "test-job"
      tasks:
        - task_key: "test-task"
          spark_python_task:
            python_file: ./test.py
          new_cluster:
            spark_version: 15.4.x-scala2.12
            node_type_id: i3.xlarge
            num_workers: 0
