bundle:
  name: wal-corrupted-test

resources:
  jobs:
    valid_job:
      name: "valid-job"
      tasks:
        - task_key: "task-a"
          spark_python_task:
            python_file: ./test.py
          new_cluster:
            spark_version: 15.4.x-scala2.12
            node_type_id: i3.xlarge
            num_workers: 0
    another_valid:
      name: "another-valid"
      tasks:
        - task_key: "task-b"
          spark_python_task:
            python_file: ./test.py
          new_cluster:
            spark_version: 15.4.x-scala2.12
            node_type_id: i3.xlarge
            num_workers: 0
