Local = true
Cloud = true
RecordRequests = false
RequiresUnityCatalog = true

Ignore = [
    ".databricks",
    "databricks.yml",
    "catalog.yml",
    "test-file-*.txt",
]

[EnvMatrix]
  DATABRICKS_BUNDLE_ENGINE = ["direct"]
