Local = false
CloudSlow = true

Ignore = [
    ".databricks",
    ".venv",
    "build",
    "dist",
    "my_test_code",
    "my_test_code.egg-info",
    "setup.py",
    "databricks.yml",
    "python_wheel_wrapper.yml",
    "empty.yml",
]
