# Kill the CLI 3 times, then allow the 4th request to succeed
[[Server]]
Pattern = "GET /api/2.0/preview/scim/v2/Me"
KillCaller = 3
Response.Body = '''
{
    "id": "123",
    "userName": "test@example.com"
}
'''
