Local = false
Cloud = true
RecordRequests = false

# Deploying identity on gcp is a SP which causes diverging output.
CloudEnvs.gcp = false

Ignore = [
    "databricks.yml.tmpl",
]

[EnvMatrix]
  DATABRICKS_BUNDLE_ENGINE = ["terraform", "direct"]
