Local = true
Cloud = true
RecordRequests = false
RunsOnDbr = true

# The current user on GCP is not a service principal. This causes diverging output since we set permissions for the current user. Thus we skip this test on GCP.
CloudEnvs.gcp = false

Ignore = [
    "databricks.yml.tmpl",
]
