[[Server]]
Pattern = "GET /api/2.0/database/instances"
Response.Body = '''
{
    "database_instances": [
        {"name": "my-database"},
        {"name": "another-database"}
    ]
}
'''

[[Server]]
Pattern = "GET /api/2.0/postgres/projects"
Response.Body = '''
{
    "projects": [
        {"name": "projects/my-project"},
        {"name": "projects/another-project"}
    ]
}
'''
