Local = true
Cloud = true
Badness = "post deployment, bundle summary should print actual name that is fully resolved"

RecordRequests = false

# The test fails with this today:
# Error: cannot create resources.synced_database_tables.my_synced_table: Cannot create more than 20 synced database table(s) per source table. (400 BAD_REQUEST)
RunsOnDbr = false

[[Repls]]
# clean up ?o=<num> suffix after URL since not all workspaces have that
Old = '\?o=\[(NUMID|ALPHANUMID)\]'
New = ''
Order = 1000

# Fake SQL endpoint for local tests
[[Server]]
Pattern = "POST /api/2.0/sql/statements/"
Response.Body = '{"status": {"state": "SUCCEEDED"}, "manifest": {"schema": {"columns": []}}}'

[[Server]]
Pattern = "DELETE /api/2.1/unity-catalog/tables/{name}"
Response.Body = '{"status": "OK"}'
