Local = true
Cloud = true
Badness = "post deployment, bundle summary should print actual name that is fully resolved"

RecordRequests = false

[[Repls]]
# clean up ?o=<num> suffix after URL since not all workspaces have that
Old = '\?o=\[(NUMID|ALPHANUMID)\]'
New = ''
Order = 1000
