[[Server]]
Pattern = "GET /api/2.1/unity-catalog/current-metastore-assignment"
Response.StatusCode = 404
Response.Body = "{ \"error\": \"Bad Target: /api/2.1/unity-catalog/current-metastore-assignment\" }"
