# Let first 2 requests pass, kill next 2, then allow rest
[[Server]]
Pattern = "GET /api/2.0/preview/scim/v2/Me"
KillCallerOffset = 2
KillCaller = 2
Response.Body = '''
{
    "id": "123",
    "userName": "test@example.com"
}
'''
