# Timeout = '5m'
Cloud = true
Local = true

[[Server]]
Pattern = "GET /api/2.1/unity-catalog/models/system.ai.llama_v3_2_1b_instruct/versions"
Response.Body = '''
{
  "model_versions": [
    {
      "version": 1
    }
  ]
}
'''
