Timeout = '30m'
Cloud = true
Local = true
CloudSlow = true

[[Server]]
Pattern = "GET /api/2.1/unity-catalog/models/system.ai.llama_v3_2_1b_instruct/versions"
Response.Body = '''
{
  "model_versions": [
    {
      "version": 1
    }
  ]
}
'''

[[Repls]]
Old = '"entity_version": "1",'
New = '"entity_version": "[VERSION]",'
