Cloud = true
RequiresUnityCatalog = true

RecordRequests = false
Ignore = [".databricks", "databricks.yml", "databricks.yml.backup", "pipeline_root"]

[Env]
DATABRICKS_BUNDLE_ENABLE_EXPERIMENTAL_YAML_SYNC = "true"

[EnvMatrix]
DATABRICKS_BUNDLE_ENGINE = ["direct", "terraform"]
