Local = true
Cloud = true
CloudSlow = true

EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["direct"]

Ignore = [
    "databricks.yml",
    "out.requests.txt",
]

[[Repls]]
Old = '\?o=\[(NUMID|ALPHANUMID)\]'
New = ''
Order = 1000

[[Repls]]
Old = 'br-[a-z0-9]+-[a-z0-9]+-[a-z0-9]+-[a-z0-9]'
New = '[BRANCH_UID]'
Order = 1

[[Repls]]
Old = '"source_branch_lsn": "0/[A-F0-9]+"'
New = '"source_branch_lsn": "[LSN]"'
Order = 1

[[Repls]]
Old = 'proj-[a-z]+-[a-z]+-[a-z0-9]+'
New = '[PROJECT_UID]'
Order = 1
