# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_stacks/resources/*
# and mlops_stacks/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for mlops_stacks Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_stacks

env:
  ARM_TENANT_ID: ${{ secrets.PROD_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.PROD_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.PROD_AZURE_SP_CLIENT_SECRET }}

jobs:
  prod:
    concurrency: mlops_stacks-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
