Local = true
Cloud = true
CloudSlow = true

EnvMatrix.DATABRICKS_BUNDLE_ENGINE = ["direct"]

Ignore = [
    "databricks.yml",
    "out.requests.txt",
]

[[Repls]]
Old = '\?o=\[(NUMID|ALPHANUMID)\]'
New = ''
Order = 1000

[[Repls]]
Old = 'proj-[a-z]+-[a-z]+-[a-z0-9]+'
New = '[PROJECT_UID]'
Order = 1
