Local = true
Cloud = true
RecordRequests = true
IsServicePrincipal = true

# On GCP, service principals do not follow UUID which results them being treated as user_name, resulting in different output
CloudEnvs.gcp = false
