Local = true
Cloud = true
RequiresUnityCatalog = true

[[Server]]
Pattern = "POST /api/2.1/unity-catalog/schemas"
Response.Body = '''
{
    "name":"test-schema-6260d50f-e8ff-4905-8f28-812345678903",
    "catalog_name":"main",
    "full_name":"main.test-schema-6260d50f-e8ff-4905-8f28-812345678903"
}
'''

[[Server]]
Pattern = "GET /api/2.1/unity-catalog/schemas/{schema_fullname}"
Response.Body = '''
{
    "name":"test-schema-6260d50f-e8ff-4905-8f28-812345678903",
    "catalog_name":"main",
    "full_name":"main.test-schema-6260d50f-e8ff-4905-8f28-812345678903",
    "comment": "This schema was created from DABs"
}
'''

[[Server]]
Pattern = "PATCH /api/2.1/unity-catalog/schemas/{schema_fullname}"

[[Server]]
Pattern = "DELETE /api/2.1/unity-catalog/schemas/{schema_fullname}"
