RecordRequests = false
Timeout = '1m'
TimeoutWindows = '10m'

# Cannot run 2 instances of this test because it uses fixed ports
EnvMatrix.DATABRICKS_CLI_DEPLOYMENT = ["terraform"]

Ignore = [
    '.venv',
    '__pycache__'
]

[[Repls]]
Old='curl/[0-9]+\.[0-9]+\.[0-9]+'
New='curl/(version)'

[[Repls]]
Old='127.0.0.1:[0-9]+'
New='127.0.0.1:$(port)'

[[Repls]]
Old='To debug your app, attach a debugger to port [0-9]+'
New='To debug your app, attach a debugger to port $(debug_port)'
